package com.paolofree.lettoreepub;

import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    private LinearLayout list;private TextView countView;private File dir;private android.content.SharedPreferences prefs;
    @Override public void onCreate(Bundle b){super.onCreate(b);dir=new File(getFilesDir(),"books");dir.mkdirs();prefs=getSharedPreferences("reader",0);build();handleOpenIntent(getIntent());}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);handleOpenIntent(intent);}
    private void handleOpenIntent(Intent intent){if(intent!=null&&Intent.ACTION_VIEW.equals(intent.getAction())&&intent.getData()!=null)importBook(intent.getData(),true);}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private TextView label(String value,float size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}

    private void build(){FrameLayout frame=new FrameLayout(this);frame.setBackgroundColor(Color.rgb(5,17,27));frame.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(14),dp(18),dp(16));frame.addView(root,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout hero=new LinearLayout(this);hero.setGravity(Gravity.CENTER_VERTICAL);hero.setPadding(dp(18),dp(15),dp(18),dp(15));GradientDrawable heroBg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(10,48,70),Color.rgb(8,29,44)});heroBg.setCornerRadius(dp(24));hero.setBackground(heroBg);hero.setElevation(dp(7));
        ImageView icon=new ImageView(this);icon.setImageResource(com.paolofree.lettoreepub.R.mipmap.ic_launcher);hero.addView(icon,new LinearLayout.LayoutParams(dp(68),dp(68)));
        LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.setPadding(dp(15),0,0,0);TextView title=label("Lettore ePub",27,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);TextView sub=label("LA TUA BIBLIOTECA VOCALE",11,Color.rgb(72,199,232));sub.setLetterSpacing(.12f);titles.addView(title);titles.addView(sub);hero.addView(titles,new LinearLayout.LayoutParams(0,-2,1));root.addView(hero);
        LinearLayout section=new LinearLayout(this);section.setGravity(Gravity.CENTER_VERTICAL);section.setPadding(dp(4),dp(22),dp(4),dp(10));TextView library=label("LA MIA LIBRERIA",14,Color.rgb(220,237,244));library.setTypeface(Typeface.DEFAULT,Typeface.BOLD);section.addView(library,new LinearLayout.LayoutParams(0,-2,1));countView=label("0 LIBRI",11,Color.rgb(255,187,51));countView.setGravity(Gravity.CENTER);countView.setPadding(dp(13),dp(7),dp(13),dp(7));countView.setBackground(shape(Color.rgb(13,38,57),18));section.addView(countView);root.addView(section);
        ScrollView scroll=new ScrollView(this);scroll.setClipToPadding(false);scroll.setPadding(0,0,0,dp(92));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        TextView signature=label("Paolo Free 1.0",11,Color.rgb(113,148,166));signature.setGravity(Gravity.CENTER);root.addView(signature,new LinearLayout.LayoutParams(-1,dp(28)));
        TextView add=label("＋",34,Color.rgb(5,17,27));add.setGravity(Gravity.CENTER);add.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable addBg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(255,201,71),Color.rgb(72,199,232)});addBg.setShape(GradientDrawable.OVAL);add.setBackground(addBg);add.setElevation(dp(12));add.setContentDescription("Aggiungi libro EPUB");add.setOnClickListener(v->chooseBook());FrameLayout.LayoutParams addLp=new FrameLayout.LayoutParams(dp(68),dp(68),Gravity.RIGHT|Gravity.BOTTOM);addLp.setMargins(0,0,dp(24),dp(48));frame.addView(add,addLp);setContentView(frame);refresh();}

    private void chooseBook(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/epub+zip");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,7);}
    private void refresh(){if(list==null)return;list.removeAllViews();File[] files=dir.listFiles((d,n)->n.toLowerCase().endsWith(".epub"));if(files==null)files=new File[0];Arrays.sort(files,(a,b)->Long.compare(b.lastModified(),a.lastModified()));countView.setText(files.length+(files.length==1?" LIBRO":" LIBRI"));if(files.length==0){LinearLayout empty=new LinearLayout(this);empty.setOrientation(LinearLayout.VERTICAL);empty.setGravity(Gravity.CENTER);empty.setPadding(dp(25),dp(65),dp(25),dp(40));TextView symbol=label("◫",54,Color.rgb(72,199,232));symbol.setGravity(Gravity.CENTER);TextView msg=label("La tua biblioteca è vuota",20,Color.WHITE);msg.setGravity(Gravity.CENTER);TextView hint=label("Tocca il pulsante + per aggiungere il primo EPUB",14,Color.rgb(150,180,195));hint.setGravity(Gravity.CENTER);hint.setPadding(0,dp(8),0,0);empty.addView(symbol);empty.addView(msg);empty.addView(hint);list.addView(empty);return;}for(File f:files)addBookCard(f);}
    private void addBookCard(File file){String title=file.getName().replaceFirst("(?i)\\.epub$","");String author="Autore non indicato";int chapters=0;try(EpubBook book=new EpubBook(file)){title=book.title;author=book.author.isEmpty()?author:book.author;chapters=book.chapters.size();}catch(Exception ignored){}final int total=chapters;final String dialogTitle=title;int current=prefs.getInt(file.getName()+"_chapter",0)+1;
        LinearLayout card=new LinearLayout(this);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(13),dp(13),dp(13),dp(13));GradientDrawable cardBg=shape(Color.rgb(10,36,53),20);cardBg.setStroke(dp(1),Color.rgb(23,74,99));card.setBackground(cardBg);card.setElevation(dp(4));LinearLayout.LayoutParams cardLp=new LinearLayout.LayoutParams(-1,dp(116));cardLp.setMargins(0,0,0,dp(12));card.setLayoutParams(cardLp);
        TextView cover=label("📖",31,Color.WHITE);cover.setGravity(Gravity.CENTER);GradientDrawable coverBg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(28,131,174),Color.rgb(22,73,112)});coverBg.setCornerRadius(dp(16));cover.setBackground(coverBg);card.addView(cover,new LinearLayout.LayoutParams(dp(78),dp(88)));
        LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(dp(14),0,dp(8),0);TextView bookTitle=label(title,18,Color.WHITE);bookTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bookTitle.setMaxLines(2);bookTitle.setEllipsize(android.text.TextUtils.TruncateAt.END);TextView by=label(author,13,Color.rgb(154,190,205));by.setSingleLine(true);by.setEllipsize(android.text.TextUtils.TruncateAt.END);TextView progress=label(total>0?"CONTINUA  •  CAPITOLO "+Math.min(current,total)+" DI "+total:"APRI IL LIBRO",11,Color.rgb(255,187,51));progress.setPadding(0,dp(8),0,0);info.addView(bookTitle);info.addView(by);info.addView(progress);card.addView(info,new LinearLayout.LayoutParams(0,-2,1));TextView open=label("›",34,Color.rgb(72,199,232));open.setGravity(Gravity.CENTER);card.addView(open,new LinearLayout.LayoutParams(dp(30),-1));
        card.setOnClickListener(v->startActivity(new Intent(this,ReaderActivity.class).putExtra("path",file.getAbsolutePath())));card.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("Eliminare il libro?").setMessage(dialogTitle).setNegativeButton("Annulla",null).setPositiveButton("Elimina",(d,w)->{file.delete();refresh();}).show();return true;});list.addView(card);}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null)importBook(d.getData(),true);}
    private void importBook(Uri uri,boolean openAfter){try{String name="libro_"+System.currentTimeMillis()+".epub";try(android.database.Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)name=c.getString(x);}}name=name.replaceAll("[^a-zA-Z0-9._ -]","_");if(!name.toLowerCase().endsWith(".epub"))name=name+".epub";File out=new File(dir,name);try(InputStream in=getContentResolver().openInputStream(uri);OutputStream os=new FileOutputStream(out)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)os.write(b,0,n);}try(EpubBook test=new EpubBook(out)){}refresh();Toast.makeText(this,"Libro aggiunto alla biblioteca",Toast.LENGTH_SHORT).show();if(openAfter)startActivity(new Intent(this,ReaderActivity.class).putExtra("path",out.getAbsolutePath()));}catch(Exception e){Toast.makeText(this,"EPUB non valido: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
