package com.paolofree.lettoreepub;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout list; File dir;
    @Override public void onCreate(Bundle b){super.onCreate(b);dir=new File(getFilesDir(),"books");dir.mkdirs();build();if(Intent.ACTION_VIEW.equals(getIntent().getAction())&&getIntent().getData()!=null)importBook(getIntent().getData());}
    TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.rgb(235,245,250));v.setTextSize(sp);v.setPadding(28,22,28,22);return v;}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.setBackgroundColor(Color.rgb(7,21,33));TextView title=text("📚  LETTORE ePUB",25);title.setTextColor(Color.rgb(72,199,232));root.addView(title);Button add=new Button(this);add.setText("＋  AGGIUNGI UN LIBRO EPUB");add.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/epub+zip");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,7);});root.addView(add);TextView sub=text("LA MIA LIBRERIA",14);root.addView(sub);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));TextView sign=text("Paolo Free 1.0",12);sign.setGravity(Gravity.CENTER);root.addView(sign);setContentView(root);refresh();}
    void refresh(){if(list==null)return;list.removeAllViews();File[] fs=dir.listFiles((d,n)->n.toLowerCase().endsWith(".epub"));if(fs==null||fs.length==0){TextView empty=text("Nessun libro. Tocca il pulsante in alto per importare il primo EPUB.",17);list.addView(empty);return;}Arrays.sort(fs,(a,b)->Long.compare(b.lastModified(),a.lastModified()));for(File f:fs){String name=f.getName().replaceFirst("(?i)\\.epub$","");try(EpubBook eb=new EpubBook(f)){name=eb.title+(eb.author.isEmpty()?"":"\n"+eb.author);}catch(Exception ignored){}Button row=new Button(this);row.setAllCaps(false);row.setText("📖  "+name);row.setTextSize(17);row.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);row.setPadding(25,20,20,20);row.setOnClickListener(v->startActivity(new Intent(this,ReaderActivity.class).putExtra("path",f.getAbsolutePath())));row.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("Eliminare il libro?").setMessage(f.getName()).setNegativeButton("Annulla",null).setPositiveButton("Elimina",(d,w)->{f.delete();refresh();}).show();return true;});list.addView(row,new LinearLayout.LayoutParams(-1,100));}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null)importBook(d.getData());}
    void importBook(Uri uri){try{String n="libro_"+System.currentTimeMillis()+".epub";try(android.database.Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)n=c.getString(x);}}n=n.replaceAll("[^a-zA-Z0-9._ -]","_");File out=new File(dir,n);try(InputStream in=getContentResolver().openInputStream(uri);OutputStream os=new FileOutputStream(out)){byte[] b=new byte[8192];int x;while((x=in.read(b))>0)os.write(b,0,x);}try(EpubBook test=new EpubBook(out)){}refresh();Toast.makeText(this,"Libro importato",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"EPUB non valido: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
