package com.paolofree.lettoreepub;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.speech.tts.*;import android.view.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.util.*;

public class ReaderActivity extends Activity implements TextToSpeech.OnInitListener {
    EpubBook book; File extracted; WebView web; TextView head,progress; LinearLayout controls; int chapter=0,size=20;String theme="Seppia";TextToSpeech tts;boolean speaking=false,paused=false;ArrayList<String> chunks=new ArrayList<>();int chunk=0;android.content.SharedPreferences prefs;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);prefs=getSharedPreferences("reader",0);try{book=new EpubBook(new File(getIntent().getStringExtra("path")));extracted=new File(getCacheDir(),"epub_"+Integer.toHexString(book.file.getAbsolutePath().hashCode()));book.extractTo(extracted);chapter=prefs.getInt(book.file.getName()+"_chapter",0);size=prefs.getInt("size",20);theme=prefs.getString("theme","Seppia");build();show();tts=new TextToSpeech(this,this);}catch(Exception e){new AlertDialog.Builder(this).setTitle("Impossibile aprire il libro").setMessage(e.getMessage()).setPositiveButton("Chiudi",(d,w)->finish()).show();}}
    Button b(String s){Button x=new Button(this);x.setText(s);x.setMinWidth(0);x.setPadding(8,0,8,0);return x;}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(7,21,33));root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(0,insets.getSystemWindowInsetTop(),0,insets.getSystemWindowInsetBottom());return insets;});LinearLayout top=new LinearLayout(this);Button back=b("‹ INDIETRO");back.setOnClickListener(v->finish());top.addView(back);head=new TextView(this);head.setTextColor(Color.WHITE);head.setTextSize(16);head.setGravity(Gravity.CENTER_VERTICAL);head.setSingleLine(true);top.addView(head,new LinearLayout.LayoutParams(0,60,1));Button menu=b("☰");menu.setOnClickListener(v->settings());top.addView(menu);root.addView(top);web=new WebView(this);web.getSettings().setJavaScriptEnabled(false);web.getSettings().setAllowFileAccess(true);web.getSettings().setBuiltInZoomControls(true);web.getSettings().setDisplayZoomControls(false);web.setWebViewClient(new WebViewClient());root.addView(web,new LinearLayout.LayoutParams(-1,0,1));controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);String[] names={"‹ CAP.","LEGGI","PAUSA","STOP","CAP. ›"};for(String n:names){Button x=b(n);x.setTextSize(11);controls.addView(x,new LinearLayout.LayoutParams(0,62,1));if(n.equals("‹ CAP."))x.setOnClickListener(v->prev());if(n.equals("CAP. ›"))x.setOnClickListener(v->next());if(n.equals("LEGGI"))x.setOnClickListener(v->speak());if(n.equals("PAUSA"))x.setOnClickListener(v->pauseResume());if(n.equals("STOP"))x.setOnClickListener(v->stopSpeak());}root.addView(controls);progress=new TextView(this);progress.setTextColor(Color.LTGRAY);progress.setGravity(Gravity.CENTER);root.addView(progress,new LinearLayout.LayoutParams(-1,35));setContentView(root);}
    void show(){chapter=Math.max(0,Math.min(chapter,book.chapters.size()-1));try{File chapterPath=book.chapterFile(extracted,chapter);String base=chapterPath.getParentFile().toURI().toString();web.loadDataWithBaseURL(base,book.html(chapter,theme,size),"text/html","UTF-8",null);head.setText(book.title);progress.setText("Capitolo "+(chapter+1)+" di "+book.chapters.size());prefs.edit().putInt(book.file.getName()+"_chapter",chapter).apply();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
    void prev(){stopSpeak();if(chapter>0){chapter--;show();}}void next(){stopSpeak();if(chapter<book.chapters.size()-1){chapter++;show();}}
    @Override public void onInit(int status){if(status==TextToSpeech.SUCCESS){tts.setLanguage(Locale.ITALIAN);tts.setSpeechRate(prefs.getFloat("rate",0.9f));tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String u){}public void onError(String u){}public void onDone(String u){runOnUiThread(()->speakNext());}});}}
    void speak(){if(tts==null)return;try{String text=book.plain(chapter);chunks.clear();for(int p=0;p<text.length();p+=3000)chunks.add(text.substring(p,Math.min(text.length(),p+3000)));chunk=0;paused=false;speaking=true;speakNext();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
    void speakNext(){if(!speaking)return;if(chunk<chunks.size()){tts.speak(chunks.get(chunk++),TextToSpeech.QUEUE_FLUSH,null,"part"+chunk);}else if(chapter<book.chapters.size()-1){chapter++;show();speak();}else stopSpeak();}
    void pauseResume(){if(tts==null)return;if(tts.isSpeaking()){tts.stop();speaking=false;paused=true;chunk=Math.max(0,chunk-1);Toast.makeText(this,"Lettura in pausa",Toast.LENGTH_SHORT).show();}else if(paused&&!chunks.isEmpty()){paused=false;speaking=true;speakNext();}else speak();}
    void stopSpeak(){speaking=false;paused=false;chunks.clear();chunk=0;if(tts!=null)tts.stop();}
    void settings(){String[] a={"Indice dei capitoli","Testo più grande","Testo più piccolo","Tema chiaro","Tema seppia","Tema scuro","Velocità voce 0,75×","Velocità voce 1×","Velocità voce 1,25×"};new AlertDialog.Builder(this).setTitle("Impostazioni di lettura").setItems(a,(d,w)->{if(w==0)index();else if(w==1){size=Math.min(34,size+2);saveLook();}else if(w==2){size=Math.max(14,size-2);saveLook();}else if(w>=3&&w<=5){theme=w==3?"Chiaro":w==4?"Seppia":"Scuro";saveLook();}else{float r=w==6?.75f:w==7?1f:1.25f;prefs.edit().putFloat("rate",r).apply();if(tts!=null)tts.setSpeechRate(r);}}).show();}
    void saveLook(){prefs.edit().putInt("size",size).putString("theme",theme).apply();show();}
    void index(){String[] x=new String[book.chapters.size()];for(int i=0;i<x.length;i++)x[i]="Capitolo "+(i+1);new AlertDialog.Builder(this).setTitle("Indice").setItems(x,(d,w)->{stopSpeak();chapter=w;show();}).show();}
    @Override protected void onDestroy(){stopSpeak();if(tts!=null)tts.shutdown();try{if(book!=null)book.close();}catch(Exception ignored){}super.onDestroy();}
}
