package com.paolofree.lettoreepub;

import android.app.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.speech.tts.*;import android.view.*;import android.webkit.*;import android.widget.*;import java.io.*;import java.util.*;

public class ReaderActivity extends Activity implements TextToSpeech.OnInitListener {
    private EpubBook book;private File extracted;private WebView web;private TextView titleView,pageView;private int chapter=0,page=0,pageCount=1,fontSize=20;private String theme="Seppia";private TextToSpeech tts;private boolean speaking=false,paused=false,turnLocked=false;private final ArrayList<String> chunks=new ArrayList<>();private int chunk=0;private float touchStartX,touchStartY;private android.content.SharedPreferences prefs;
    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);prefs=getSharedPreferences("reader",0);try{book=new EpubBook(new File(getIntent().getStringExtra("path")));extracted=new File(getCacheDir(),"epub_"+Integer.toHexString(book.file.getAbsolutePath().hashCode()));book.extractTo(extracted);chapter=prefs.getInt(key("chapter"),0);page=prefs.getInt(key("page"),0);fontSize=prefs.getInt("size",20);theme=prefs.getString("theme","Seppia");buildInterface();showChapter(true);tts=new TextToSpeech(this,this);}catch(Exception e){new AlertDialog.Builder(this).setTitle("Impossibile aprire il libro").setMessage(e.getMessage()).setPositiveButton("Chiudi",(d,w)->finish()).show();}}
    private String key(String suffix){return book.file.getName()+"_"+suffix;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable panel(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private TextView iconButton(String symbol,int accent){TextView v=new TextView(this);v.setText(symbol);v.setTextColor(Color.WHITE);v.setTextSize(22);v.setGravity(Gravity.CENTER);GradientDrawable g=panel(Color.rgb(13,38,57),28);g.setStroke(dp(2),accent);v.setBackground(g);v.setElevation(dp(5));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(58),1);lp.setMargins(dp(5),dp(6),dp(5),dp(6));v.setLayoutParams(lp);return v;}
    private void buildInterface(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(5,17,27));root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(8),dp(5),dp(8),dp(5));top.setBackground(panel(Color.rgb(8,29,44),0));TextView back=iconButton("‹",Color.rgb(72,199,232));back.setLayoutParams(new LinearLayout.LayoutParams(dp(54),dp(54)));back.setOnClickListener(v->finish());top.addView(back);
        LinearLayout heading=new LinearLayout(this);heading.setOrientation(LinearLayout.VERTICAL);heading.setPadding(dp(12),0,dp(8),0);titleView=new TextView(this);titleView.setTextColor(Color.WHITE);titleView.setTextSize(17);titleView.setSingleLine(true);titleView.setEllipsize(android.text.TextUtils.TruncateAt.END);TextView subtitle=new TextView(this);subtitle.setText("LETTORE EPUB • PAOLO FREE");subtitle.setTextColor(Color.rgb(72,199,232));subtitle.setTextSize(10);subtitle.setLetterSpacing(.12f);heading.addView(titleView);heading.addView(subtitle);top.addView(heading,new LinearLayout.LayoutParams(0,dp(60),1));TextView menu=iconButton("☰",Color.rgb(255,187,51));menu.setLayoutParams(new LinearLayout.LayoutParams(dp(54),dp(54)));menu.setOnClickListener(v->settings());top.addView(menu);root.addView(top);
        FrameLayout frame=new FrameLayout(this);frame.setPadding(dp(7),dp(7),dp(7),dp(5));web=new WebView(this);web.setBackgroundColor(Color.TRANSPARENT);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(true);web.getSettings().setBuiltInZoomControls(false);web.setOverScrollMode(View.OVER_SCROLL_NEVER);web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView view,String url){preparePages();}});web.setOnTouchListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_DOWN){touchStartX=event.getX();touchStartY=event.getY();return true;}if(event.getAction()==MotionEvent.ACTION_UP){float dx=event.getX()-touchStartX,dy=event.getY()-touchStartY;if(Math.abs(dx)>dp(55)&&Math.abs(dx)>Math.abs(dy)){if(dx<0)nextPage();else previousPage();}else if(Math.abs(dx)<dp(18)&&Math.abs(dy)<dp(18)){if(event.getX()>web.getWidth()*.68f)nextPage();else if(event.getX()<web.getWidth()*.32f)previousPage();}return true;}return true;});GradientDrawable paper=panel(Color.rgb(252,248,238),18);paper.setStroke(dp(1),Color.rgb(39,94,122));web.setBackground(paper);web.setClipToOutline(true);frame.addView(web,new FrameLayout.LayoutParams(-1,-1));root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));
        pageView=new TextView(this);pageView.setTextColor(Color.rgb(164,191,205));pageView.setTextSize(12);pageView.setGravity(Gravity.CENTER);root.addView(pageView,new LinearLayout.LayoutParams(-1,dp(28)));
        LinearLayout dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(48),0,dp(48),dp(5));dock.setBackground(panel(Color.rgb(8,29,44),22));TextView read=iconButton("🔊",Color.rgb(255,187,51));read.setContentDescription("Leggi ad alta voce");read.setOnClickListener(v->speak());TextView pause=iconButton("Ⅱ",Color.rgb(72,199,232));pause.setContentDescription("Pausa o riprendi");pause.setOnClickListener(v->pauseResume());TextView stop=iconButton("■",Color.rgb(235,92,92));stop.setContentDescription("Ferma lettura");stop.setOnClickListener(v->stopSpeak());dock.addView(read);dock.addView(pause);dock.addView(stop);root.addView(dock);setContentView(root);}
    private void showChapter(boolean restore){chapter=Math.max(0,Math.min(chapter,book.chapters.size()-1));if(!restore)page=0;pageCount=1;try{File path=book.chapterFile(extracted,chapter);web.loadDataWithBaseURL(path.getParentFile().toURI().toString(),book.html(chapter,theme,fontSize),"text/html","UTF-8",null);titleView.setText(book.title);updateIndicator();savePosition();}catch(Exception e){Toast.makeText(this,"Errore pagina: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void preparePages(){String js="(function(){var w=window.innerWidth,h=window.innerHeight;document.documentElement.style.cssText+=';width:'+w+'px!important;height:'+h+'px!important;margin:0!important;padding:0!important;overflow:hidden!important;';document.body.style.cssText+=';box-sizing:border-box!important;width:'+w+'px!important;max-width:none!important;height:auto!important;max-height:none!important;margin:0!important;padding:24px 30px 40px!important;column-width:auto!important;column-count:auto!important;column-gap:normal!important;overflow:visible!important;';var all=document.querySelectorAll('p,div,span,li,section,article');for(var i=0;i<all.length;i++){all[i].style.wordSpacing='normal';all[i].style.letterSpacing='normal';all[i].style.breakInside='auto';all[i].style.pageBreakInside='auto';}window.readerPageOffsets=[0];var usable=Math.max(200,h-48),max=document.body.scrollHeight-h+40,current=0;while(current<max){var wanted=current+usable,best=wanted;var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);var node,found=false;while(node=walker.nextNode()){if(!node.nodeValue.trim())continue;var range=document.createRange();range.selectNodeContents(node);var rects=range.getClientRects();for(var r=0;r<rects.length;r++){var top=rects[r].top+window.scrollY;if(top>=wanted-38){best=Math.max(current+80,top-24);found=true;break;}}if(found)break;}if(!found)best=Math.min(max,wanted);if(best<=current+60)best=Math.min(max,current+usable);window.readerPageOffsets.push(Math.round(best));current=best;}return window.readerPageOffsets.length;})()";web.evaluateJavascript(js,result->{try{pageCount=Math.max(1,(int)Math.ceil(Double.parseDouble(result.replace("\"",""))));}catch(Exception ignored){pageCount=1;}page=Math.min(page,pageCount-1);moveToPage(false);});}
    private void moveToPage(boolean animate){String behavior=animate?"smooth":"auto";web.evaluateJavascript("(function(){var y=(window.readerPageOffsets&&window.readerPageOffsets["+page+"]!=null)?window.readerPageOffsets["+page+"]:0;window.scrollTo({left:0,top:y,behavior:'"+behavior+"'});})()",null);updateIndicator();savePosition();new Handler(Looper.getMainLooper()).postDelayed(()->turnLocked=false,animate?450:80);}
    private boolean lockTurn(){if(turnLocked)return false;turnLocked=true;return true;}
    private void previousPage(){if(!lockTurn())return;stopSpeak();if(page>0){page--;moveToPage(true);}else if(chapter>0){chapter--;page=9999;showChapter(true);}else turnLocked=false;}
    private void nextPage(){if(!lockTurn())return;stopSpeak();if(page<pageCount-1){page++;moveToPage(true);}else if(chapter<book.chapters.size()-1){chapter++;page=0;showChapter(false);}else{turnLocked=false;Toast.makeText(this,"Fine del libro",Toast.LENGTH_SHORT).show();}}
    private void updateIndicator(){if(pageView!=null)pageView.setText("CAPITOLO "+(chapter+1)+" / "+book.chapters.size()+"     •     PAGINA "+(page+1)+" / "+pageCount);}private void savePosition(){prefs.edit().putInt(key("chapter"),chapter).putInt(key("page"),page).apply();}
    @Override public void onInit(int status){if(status==TextToSpeech.SUCCESS){tts.setLanguage(Locale.ITALIAN);tts.setSpeechRate(prefs.getFloat("rate",.9f));tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onError(String id){}public void onDone(String id){runOnUiThread(()->speakNext());}});}}
    private void speak(){if(tts==null)return;try{String text=book.plain(chapter);chunks.clear();for(int p=0;p<text.length();p+=3000)chunks.add(text.substring(p,Math.min(text.length(),p+3000)));chunk=0;paused=false;speaking=true;speakNext();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
    private void speakNext(){if(!speaking)return;if(chunk<chunks.size())tts.speak(chunks.get(chunk++),TextToSpeech.QUEUE_FLUSH,null,"part"+chunk);else if(chapter<book.chapters.size()-1){chapter++;page=0;showChapter(false);speak();}else stopSpeak();}
    private void pauseResume(){if(tts==null)return;if(tts.isSpeaking()){tts.stop();speaking=false;paused=true;chunk=Math.max(0,chunk-1);Toast.makeText(this,"Lettura in pausa",Toast.LENGTH_SHORT).show();}else if(paused&&!chunks.isEmpty()){paused=false;speaking=true;speakNext();}else speak();}private void stopSpeak(){speaking=false;paused=false;chunks.clear();chunk=0;if(tts!=null)tts.stop();}
    private void settings(){String[] options={"Indice dei capitoli","Testo più grande","Testo più piccolo","Tema chiaro","Tema seppia","Tema scuro","Voce lenta 0,75×","Voce normale 1×","Voce veloce 1,25×"};new AlertDialog.Builder(this).setTitle("Personalizza lettura").setItems(options,(d,w)->{if(w==0)showIndex();else if(w==1){fontSize=Math.min(34,fontSize+2);saveLook();}else if(w==2){fontSize=Math.max(14,fontSize-2);saveLook();}else if(w>=3&&w<=5){theme=w==3?"Chiaro":w==4?"Seppia":"Scuro";saveLook();}else{float rate=w==6?.75f:w==7?1f:1.25f;prefs.edit().putFloat("rate",rate).apply();if(tts!=null)tts.setSpeechRate(rate);}}).show();}
    private void saveLook(){prefs.edit().putInt("size",fontSize).putString("theme",theme).apply();page=0;showChapter(false);}private void showIndex(){String[] items=new String[book.chapters.size()];for(int i=0;i<items.length;i++)items[i]="Capitolo "+(i+1);new AlertDialog.Builder(this).setTitle("Indice del libro").setItems(items,(d,w)->{stopSpeak();chapter=w;page=0;showChapter(false);}).show();}
    @Override protected void onDestroy(){stopSpeak();if(tts!=null)tts.shutdown();try{if(book!=null)book.close();}catch(Exception ignored){}super.onDestroy();}
}
