plugins { id 'com.android.application' }

android {
    namespace 'com.paolofree.lettoreepub'
    compileSdk 36

    defaultConfig {
        applicationId 'com.paolofree.lettoreepub'
        minSdk 26
        targetSdk 36
        versionCode 15
        versionName '1.14'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
